# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [114]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [115]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [116]:
print(np.__version__)

1.18.1


#### 3. Create a null vector of size 10 (★☆☆)

In [117]:
v = np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [118]:
print(v.size)

10


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [119]:
hint(5)
answer(5)
%run python -c "import numpy; numpy.info(numpy.add)"

ERROR:root:File `'python.py'` not found.
hint: np.info
%run `python -c "import numpy; numpy.info(numpy.add)"`


#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [120]:
v6 = np.zeros(10)
v6[4] = 1
print(v6)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [121]:
v7 = np.arange(10,50)
print(v7)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [122]:
v8 = v7[::-1]
print(v8)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [123]:
v9 = np.reshape(np.arange(0,9),newshape = (3,3))
print(v9)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [124]:
v10 = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [125]:
v11 = np.eye(3)
print(v11)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [126]:
v12 = np.random.random((3,3,3))
print(v12)

[[[0.86676035 0.7939426  0.29393998]
  [0.9807375  0.99717597 0.72059732]
  [0.329211   0.59683406 0.63035093]]

 [[0.73289087 0.15388018 0.2286666 ]
  [0.49232891 0.92511431 0.79599578]
  [0.48916401 0.64920466 0.48409552]]

 [[0.63200675 0.66198277 0.0330042 ]
  [0.78964256 0.49754449 0.9429286 ]
  [0.29226533 0.39405643 0.6289192 ]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [127]:
v13 = np.random.random((10,10))
print(v13)
print(f'min = {v13.min()}')
print(f'max = {v13.max()}')

[[0.4879779  0.78760142 0.08637178 0.67255912 0.17425516 0.66225314
  0.86746761 0.74104506 0.51833916 0.86625432]
 [0.62587396 0.81512423 0.33968638 0.91555643 0.71780016 0.49134833
  0.63074804 0.14656523 0.22456138 0.91222689]
 [0.27800043 0.20273113 0.5986051  0.07524307 0.51075691 0.85038021
  0.26491009 0.20634281 0.59404358 0.30302972]
 [0.74130289 0.2098199  0.66578108 0.87342914 0.37377125 0.64920147
  0.34082247 0.48144463 0.36788714 0.36327002]
 [0.14359221 0.87616612 0.95585493 0.51538853 0.68988964 0.9859802
  0.14173376 0.6467702  0.18196716 0.30400461]
 [0.74337377 0.05572824 0.18998087 0.0638153  0.20211866 0.60052447
  0.92861493 0.68106349 0.1386037  0.54755662]
 [0.22523284 0.27049509 0.33623022 0.84470893 0.29911832 0.26823812
  0.72097501 0.80862625 0.98566858 0.41599512]
 [0.36128687 0.60346912 0.82797722 0.46551257 0.54224527 0.58314033
  0.71836604 0.49708191 0.11728765 0.93794458]
 [0.43066182 0.40757661 0.09717895 0.17997613 0.68475708 0.33336383
  0.94840237 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [128]:
v14 = np.random.random(30)
print(v14)
print(f'mean = {v14.mean()}')

[0.89825244 0.46402111 0.47315978 0.36441463 0.80630758 0.82697771
 0.6543218  0.26330644 0.43885956 0.22291235 0.86621198 0.63029762
 0.72469032 0.14991493 0.28604886 0.03076993 0.73235445 0.29018099
 0.16309316 0.70778382 0.57791407 0.75522623 0.46006109 0.41037158
 0.00356636 0.31247359 0.71195654 0.39704025 0.52590318 0.27555783]
mean = 0.48079833986308285


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [129]:
v15 = np.ones((3,3))
v15[1:-1,1:-1] = 0
print(v15)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [130]:
v16 = np.pad(np.arange(2,5),1)
print(v16)

[0 2 3 4 0]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [131]:
print(0 * np.nan, np.nan)
print(np.nan == np.nan, False)
print(np.inf > np.nan, False)
print(np.nan - np.nan, np.nan)
print(np.nan in set([np.nan]), True)
print(0.3 == 3 * 0.1, False)

nan nan
False False
False False
nan nan
True True
False False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [132]:
v18 = np.zeros((5,5))
for i in range(1,v18[0].size):
    v18[i,i-1] = i
print(v18)

Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [133]:
v19 = np.zeros((8,8))
v19[1::2,::2] = 1
v19[::2,1::2] = 1
print(v19)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [134]:
print(np.unravel_index(99, (6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [135]:
v21 = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(v21)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [149]:
v22 = np.random.random((5,5))
v22 = (v22 - v22.mean()) / v22.std()
print(v22)

[[ 0.84698609  0.66979059  1.16435102 -1.52946673 -0.6669419 ]
 [ 0.91389111  1.5557453  -1.32298675 -0.12000922 -0.17883981]
 [-0.97272323  0.8880163   1.69977247 -0.91996052  0.24528918]
 [-0.5304837  -0.73270615 -1.53491037 -0.42487578  0.13276418]
 [ 1.03430797 -1.02521499 -1.12090633  0.46400303  1.46510823]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [153]:
v23 = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(v23)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [159]:
a = np.random.random((5,3))
b = np.random.random((3,2))
c = a @ b
print(a)
print(b)
print(c)
print(np.dot(a,b))

[[0.17410248 0.7653751  0.11529956]
 [0.31024882 0.95760426 0.49465887]
 [0.8308075  0.87995008 0.8355084 ]
 [0.15119567 0.32574719 0.85611901]
 [0.42913979 0.33759893 0.08942317]]
[[0.81897441 0.13937695]
 [0.61085641 0.21047622]
 [0.4008166  0.4624495 ]]
[[0.65633374 0.23867935]
 [1.03731203 0.4735492 ]
 [1.55281886 0.68738442]
 [0.66595686 0.48554704]
 [0.59352126 0.17222244]]
[[0.65633374 0.23867935]
 [1.03731203 0.4735492 ]
 [1.55281886 0.68738442]
 [0.66595686 0.48554704]
 [0.59352126 0.17222244]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [162]:
v25 = np.arange(11)
v25[(3 < v25) & (v25 <= 8)] *= -1
print(v25)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [163]:
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [168]:
Z = arange(1,10)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
# print(Z<Z>Z)

[        1         4        27       256      3125     46656    823543
  16777216 387420489]
[  1   2   4   8  16  32  64 128 256]
[False False False False False False False False False]
[0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [170]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


#### 29. How to round away from zero a float array ? (★☆☆)

In [173]:
v29 = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(v29)), v29))

[ -1. -10.  10.  -2.  -5.  -3.   5.  -5.  -1.   8.]


#### 30. How to find common values between two arrays? (★☆☆)

In [175]:
a = arange(1,10)
b = arange(6,15)
print(np.intersect1d(a,b))

[6 7 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)